//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evote
{
    using System;
    using System.Collections.Generic;
    
    public partial class activityLog
    {
        public int Id { get; set; }
        public string fullname { get; set; }
        public string membership_number { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string contestantId { get; set; }
    }
}
