//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evote
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contestant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contestant()
        {
            this.voteLogs = new HashSet<voteLog>();
        }
    
        public int Id { get; set; }
        public Nullable<int> VotingSessionId { get; set; }
        public string manifesto { get; set; }
        public string CampaignPictureName { get; set; }
        public byte[] CampaignPictureContent { get; set; }
        public string CampaignPictureFileType { get; set; }
        public Nullable<int> voteNumber { get; set; }
        public Nullable<int> BIId { get; set; }
        public Nullable<decimal> percentageVote { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> MemberId { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    
        public virtual EligibleMember EligibleMember { get; set; }
        public virtual VotingSession VotingSession { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<voteLog> voteLogs { get; set; }
    }
}
