//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evote
{
    using System;
    using System.Collections.Generic;
    
    public partial class EligibleMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EligibleMember()
        {
            this.Committee_member = new HashSet<Committee_member>();
            this.Contestants = new HashSet<Contestant>();
            this.voteLogs = new HashSet<voteLog>();
        }
    
        public int Id { get; set; }
        public string fullname { get; set; }
        public string phone_number { get; set; }
        public string membership_number { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string confirmPassword { get; set; }
        public string hash { get; set; }
        public string vote_status { get; set; }
        public string ImageName { get; set; }
        public byte[] ImageContent { get; set; }
        public string ImageFileType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Committee_member> Committee_member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contestant> Contestants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<voteLog> voteLogs { get; set; }
    }
}
