//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evote
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hrEntities : DbContext
    {
        public hrEntities()
            : base("name=hrEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activityLog> activityLogs { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<BI> BIs { get; set; }
        public virtual DbSet<Committee_member> Committee_member { get; set; }
        public virtual DbSet<Contestant> Contestants { get; set; }
        public virtual DbSet<EligibleMember> EligibleMembers { get; set; }
        public virtual DbSet<membershipType> membershipTypes { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<post> posts { get; set; }
        public virtual DbSet<voteLog> voteLogs { get; set; }
        public virtual DbSet<VotingSession> VotingSessions { get; set; }
        public virtual DbSet<winner> winners { get; set; }
    }
}
