//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evote
{
    using System;
    using System.Collections.Generic;
    
    public partial class voteLog
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public Nullable<int> contestantId { get; set; }
        public Nullable<int> VotingSessionId { get; set; }
        public Nullable<int> memberId { get; set; }
    
        public virtual Contestant Contestant { get; set; }
        public virtual EligibleMember EligibleMember { get; set; }
        public virtual VotingSession VotingSession { get; set; }
    }
}
