//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evote
{
    using System;
    using System.Collections.Generic;
    
    public partial class VotingSession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VotingSession()
        {
            this.Contestants = new HashSet<Contestant>();
            this.voteLogs = new HashSet<voteLog>();
        }
    
        public int Id { get; set; }
        public string postImageName { get; set; }
        public byte[] postImageContent { get; set; }
        public string postImageFileType { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.TimeSpan> startTime { get; set; }
        public Nullable<System.DateTime> closeDate { get; set; }
        public Nullable<System.TimeSpan> closeTime { get; set; }
        public Nullable<System.DateTime> startDateTime { get; set; }
        public Nullable<System.DateTime> closeDateTime { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<bool> status { get; set; }
        public string moment { get; set; }
        public Nullable<int> BIId { get; set; }
        public string VotingSessionName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contestant> Contestants { get; set; }
        public virtual Position Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<voteLog> voteLogs { get; set; }
    }
}
